; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = watch

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    electroniccats/MPU6050
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library


[env:watch]
build_src_filter = -<*> +<watch_ui_test.cpp>

[env:i2cdebug]
build_src_filter = -<*> +<i2c_debug.cpp>